# Generated by Django 2.2.4 on 2021-03-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20210318_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='academy_name',
            field=models.CharField(default='SOME STRING', max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='belt',
            field=models.CharField(default='SOME STRING', max_length=45),
        ),
    ]
